"""
prism-predict-pipe — analytical pipe baseline for new models (no msprof needed).

Reads:
- A model YAML with ``gemm_spec:`` block (e.g. ``models/regime/<X>.yaml``)
- An arch YAML (e.g. ``arch/ascend_910b4_for_sweep_v2.yaml``)
- Fitted host_gap / kernel_gap constants from
  ``data/calibration/predict_pipe_params.json`` (generated by ``fit.py``)

Writes:
- A pipe-baseline JSON in the same schema as
  ``data/calibration/pipe_baseline_per_model.json`` so the result is directly
  consumable by ``prism-sweep`` and ``prism-ceiling``.

CLI::

    prism-predict-pipe \\
        --model models/regime/modernbert_base_prefill_S4096.yaml \\
        --arch  arch/ascend_910b4_for_sweep_v2.yaml \\
        --batch 1 \\
        --output data/calibration/predict_pipe_modernbert.json

    # Optional: refit constants from msprof baseline first
    prism-predict-pipe --refit-params

    # Optional: append/overwrite into the main pipe baseline file
    prism-predict-pipe ... --merge-into data/calibration/pipe_baseline_per_model.json
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, Mapping, Tuple

import yaml

from prism import data_root_or_fallback

from .fit import fit_all_and_save
from .model_spec import (ModelSpec, compute_gemm_ops, compute_vector_ops,
                         estimate_n_kernels, estimate_n_vector_kernels)
from . import physics

logger = logging.getLogger(__name__)

_FP16_BYTES = 2

# ─────────────────────────────────────────────────────────────────────────
# Precision档 — 只缩放 CUBE/GEMM 路径，Vector(AIV) 路径保持 FP16。
#
# 物理依据：真实混合精度量化只把 matmul(权重/激活)降精度，norm/softmax/残差
# 仍跑 FP16/FP32(在 AIV 上)。因此：
#   • byte_factor：权重+激活的字节宽(相对 FP16=2B) → 影响 mte1/mte2/fixpipe 访存时间
#   • mac_mult   ：CUBE MAC 吞吐倍数(相对 FP16) → 影响 mac 计算时间(÷mac_mult)
#   • host_gap / kernel_gap / n_kernels 不变(同一张计算图,kernel 数与调度不变)
#
# int8 在 910B 上可直接实测(AMCT 量化);fp8/fp4 是"910B-like cube"的下一代代理:
# 默认按"密度减半即吞吐翻倍"的均衡缩放(fp8≈int8, fp4=2×int8)。若要建模问题里
# 给出的非对称下一代(FP8=200T / FP4=800T,算力 4× 而密度仅 2×),用 --mac-mult
# 显式覆盖 fp4 的吞吐倍数(见 docs/findings/etbert_fp8_fp4_910b_analysis.md)。
# ─────────────────────────────────────────────────────────────────────────
# (byte_factor vs FP16, cube MAC throughput mult vs FP16, fixpipe quant-tax mult)
# fixpipe_tax_mult 来自 910B4 ET-BERT 实测（2026-06-05）：量化部署引入 requant
# (AscendQuant + 融合 dequant)，实测 INT8 fixpipe ≈ 2.65× FP16(b1 196/74µs)。
# FP4 requant 略重取 3.0。--ideal-fixpipe 把它置 1.0（假设下一代 fixpipe 吸收量化）。
_PRECISIONS: Dict[str, Tuple[float, float, float]] = {
    # name : (byte_factor, mac_mult, fixpipe_quant_tax_mult)
    "fp16": (1.0,  1.0, 1.00),   # 910B 原生, 280 TFLOPS, 2B — 已实测
    "int8": (0.5,  2.0, 2.65),   # 910B 原生, 560 TOPS, 1B — 已实测(AMCT)，fixpipe 2.65×
    "fp8":  (0.5,  2.0, 2.65),   # 下一代代理: 同 int8 密度/吞吐/量化税
    "fp4":  (0.25, 4.0, 3.00),   # 下一代代理: 0.5B, 4×, requant 略重
}


def _precision_factors(precision: str,
                       mac_mult_override: "float | None" = None,
                       ideal_fixpipe: bool = False,
                       ) -> Tuple[float, float, float]:
    """Return (byte_factor, mac_mult, fixpipe_tax_mult) for a precision tag.

    ``mac_mult_override`` models an asymmetric next-gen cube (e.g. FP4=800T on a
    part whose FP8=200T → mac_mult=4 while density only 2×).
    ``ideal_fixpipe`` zeros the measured quantization fixpipe tax (next-gen
    fixpipe absorbs quant/dequant).
    """
    key = (precision or "fp16").lower()
    if key not in _PRECISIONS:
        raise ValueError(
            f"unknown precision {precision!r}; choose from {sorted(_PRECISIONS)}")
    byte_factor, mac_mult, fixpipe_tax = _PRECISIONS[key]
    if mac_mult_override is not None:
        mac_mult = float(mac_mult_override)
    if ideal_fixpipe:
        fixpipe_tax = 1.0
    return byte_factor, mac_mult, fixpipe_tax


def _arch_dict_from_yaml(arch_yaml_path: Path | str) -> Dict[str, float]:
    """Load arch YAML and flatten to the keys physics.py needs.

    Accepts both ``arch/ascend_910b4_for_sweep_v2.yaml`` style (with nested
    ``chip:`` block) and flat dicts.
    """
    with open(arch_yaml_path, encoding="utf-8") as f:
        doc = yaml.safe_load(f)

    # Some arch YAMLs wrap fields under "chip:", others are flat.
    chip = doc.get("chip", doc)
    arch = {
        "n_cores":         float(chip.get("n_cores", 24)),
        "cube_m":          float(chip.get("cube_m", 16)),
        "cube_n":          float(chip.get("cube_n", 16)),
        "cube_k":          float(chip.get("cube_k", 16)),
        "clock_ghz":       float(chip.get("clock_ghz", 1.6)),
        "hbm_bw_gbs":      float(chip.get("hbm_bw_gbs", 392.0)),
        "l2_mb":           float(chip.get("l2_mb", 96.0)),
        "l1_l0_bw_gbs":    float(chip.get("l1_l0_bw_gbs", 2048.0)),
        "fixpipe_bw_gbs":  float(chip.get("fixpipe_bw_gbs", 4096.0)),
        "ub_l1_bw_gbs":    float(chip.get("ub_l1_bw_gbs", 2048.0)),
        "aiv_per_aic":     float(chip.get("aiv_per_aic", 2)),
        "aiv_lanes_per_aiv": float(chip.get("aiv_lanes_per_aiv", 128)),
    }
    arch["cube_total_macs"] = arch["n_cores"] * arch["cube_m"] * arch["cube_n"] * arch["cube_k"]
    arch["aiv_total_throughput"] = arch["n_cores"] * arch["aiv_per_aic"] * arch["aiv_lanes_per_aiv"]
    physics.require_arch_keys(arch)
    return arch


# ─────────────────────────────────────────────────────────────────────────
# AIV multi-factor physics model (Issue #2 P2, replaces P1 archetype α).
#
# Root-cause analysis (docs/methodology/09_aiv_prediction_gap_analysis.md)
# identified 6 factors missed by the linear α model: per-kernel overhead,
# CANN repeat-parameter derating, UB↔L1 small-payload derating, HBM bus
# contention, AIC/AIV sync idle, and operator heterogeneity.
#
# Method A replaces ``aiv_time = α_archetype × aic_time`` (LOO CV 19%,
# OOS 51%+) with 5-factor physics formula + 5 fittable parameters.
# See §4 "改进路线提案" in 09_aiv_prediction_gap_analysis.md.
# ─────────────────────────────────────────────────────────────────────────

def _compute_aiv_data(spec: ModelSpec, batch: int = 1):
    """Compute AIV data volumes including attention softmax correction.

    Returns: (data_MB, attn_frac, n_vk, vec_ops, inter_bytes, output_b, attn_softmax_bytes)
    """
    vec_ops, inter_bytes = compute_vector_ops(spec)
    _, _, _, output_b = compute_gemm_ops(spec)

    factor = float(batch)

    # Critical fix: add attention softmax data volume — O(S²) per head per layer.
    # compute_vector_ops() has softmax as L*H*S*3 (missing a factor of S),
    # and inter_bytes misses the attention score read/write entirely.
    # Rather than changing compute_vector_ops (would break other consumers),
    # we account for it here.
    attn_softmax_bytes = float(spec.layers * spec.n_heads
                               * spec.S * spec.S * _FP16_BYTES * 2) * factor
    data_bytes = inter_bytes * factor + output_b * 0.5 * factor + attn_softmax_bytes
    data_MB = data_bytes / 1e6

    # attn_frac is a model geometry property, independent of batch.
    # compute_attention_fraction uses per-batch attn_bytes, so pass per-batch data.
    attn_frac = physics.compute_attention_fraction(
        spec.layers, spec.n_heads, spec.S, data_bytes / float(max(1, batch)))

    n_vk = estimate_n_vector_kernels(spec)
    return data_MB, attn_frac, n_vk, vec_ops, inter_bytes, output_b, attn_softmax_bytes


def _compute_aiv_data_dict(spec: ModelSpec, batch: int = 1) -> dict:
    """v5 helper: return AIV data components as a dict (physics_v5 consumes)."""
    data_MB, attn_frac, n_vk, vec_ops, inter_bytes, output_b, attn_softmax_bytes = \
        _compute_aiv_data(spec, batch)
    factor = float(batch)
    return {
        "inter_bytes": inter_bytes * factor + attn_softmax_bytes,  # AIV MTE2 read
        "output_bytes": output_b * 0.5 * factor,                   # AIV MTE3 out
        "vec_ops": vec_ops * factor,
        "n_vector_kernels": n_vk,
        "attn_frac": attn_frac,
    }


def predict_aiv_v2(spec: ModelSpec, arch: Mapping[str, float],
                   fitted_params: Mapping[str, float],
                   batch: int = 1) -> dict:
    """Empirical multi-factor AIV prediction (Method B v4, Issue #2 P2).

    The pure-physics AIV model (v2) underestimates by 19–1263× because:
      - ``compute_vector_ops()`` misses O(S²) attention softmax intermediates
      - CANN per-kernel overhead is 100–1000× above Verrocchio's 40 ns (init)
      - Peak throughput derating (repeat, UB BW) compounds multiplicatively

    v4 (Method B) replaces the 3-bucket discrete amplification with a
    **continuous** function of two workload features:

        attn_frac = O(S²) attention softmax bytes / total AIV data bytes
        w_proxy   = approximate weight size in MB

    The amplification is:

        amp = max(0.1, a0 + a1 × attn_frac + a2 × w_proxy/1000)  [prefill]
        amp = amp_decode                                            [decode]

    This resolves the key failure of the 3-bucket system: GPT-2 (attn_frac=0.56)
    was lumped with BERT (attn_frac=0.24) in the "small" bucket, but GPT-2
    actually needs amp ≈ 2.0 while BERT needs ≈ 0.9. The continuous function
    captures this smoothly.

    The result is split into pseudo-pipe components (vec, mte2, mte3, scalar,
    idle) using physics-derived ratios for downstream schema compatibility.

    Returns: dict with keys ``{vec, mte2, mte3, scalar, idle}`` in μs.
    """
    data_MB, attn_frac, n_vk, vec_ops, inter_bytes, output_b, attn_softmax_bytes = \
        _compute_aiv_data(spec, batch)

    factor = float(batch)

    # ── Empirical linear model ──
    C_kernel = float(fitted_params.get("aiv_C_kernel_us", 16.0))
    C_data = float(fitted_params.get("aiv_C_data_us", 3.0))

    # ── Continuous amplification (Method B, replaces 3-bucket archetype) ──
    w_proxy = physics.weight_proxy_mb(spec.layers, spec.d_model, spec.d_ff)

    if spec.S == 1:
        # Decode regime: separate constant (fundamentally different behavior)
        amp = float(fitted_params.get("aiv_amp_decode", 1.5))
    else:
        # Prefill: continuous function of attn_frac and (w_proxy/1000)².
        #
        # The squared w_proxy term is *empirically* fit — chosen because linear
        # scaling (w_proxy/1000) gave only 3.4× dynamic range over training
        # configs (Net-Trans 0.005 → Qwen3 0.763), insufficient for the 11×
        # amp range needed to fit Qwen3 vs BERT simultaneously. Squaring
        # expands range to 11.4× (0.000025 → 0.582), which made the joint
        # fit converge from 24% MAE → 4.9% MAE.
        #
        # There is a plausible-but-not-confirmed physical hand-wave: tile
        # re-fetching overhead may scale roughly with (n_tiles × L1-miss-
        # probability), both of which grow with weight_MB → product is
        # super-linear. Not validated against msprof tile-trace data; treat
        # the exponent as a hyperparameter that may need re-fitting when new
        # measured configs (especially weight_proxy ∈ [200, 600] MB band) are
        # added to the training set.
        a0 = float(fitted_params.get("aiv_amp_a0", -0.2))
        a1 = float(fitted_params.get("aiv_amp_a1", 4.0))
        a2 = float(fitted_params.get("aiv_amp_a2", 14.0))
        wp_scaled = (w_proxy / 1000.0) ** 2
        amp = max(0.1, a0 + a1 * attn_frac + a2 * wp_scaled)

    aiv_time = (n_vk * C_kernel + data_MB * C_data) * amp

    # ── Split into pseudo-pipe components using physics ratios ──
    # This preserves the {vec, mte2, mte3, scalar, idle} schema expected
    # by downstream sweep/ceiling tools.
    T_vec_raw = physics.aiv_vec(vec_ops * factor, arch)
    T_mte2_raw = physics.aiv_mte2(inter_bytes * factor + attn_softmax_bytes, arch)
    T_mte3_raw = physics.aiv_mte3(output_b * 0.5 * factor, arch)
    total_raw = T_vec_raw + T_mte2_raw + T_mte3_raw

    if total_raw > 0:
        f_vec = T_vec_raw / total_raw
        f_mte2 = T_mte2_raw / total_raw
        f_mte3 = T_mte3_raw / total_raw
    else:
        f_vec = f_mte2 = f_mte3 = 1.0 / 3.0

    active_frac = 0.70
    T_active = aiv_time * active_frac
    T_scalar_overhead = n_vk * 0.19      # per-kernel scalar dispatch (small term)
    T_idle = max(0.0, aiv_time - T_active - T_scalar_overhead)

    return {
        "vec":    T_active * f_vec,
        "mte2":   T_active * f_mte2,
        "mte3":   T_active * f_mte3,
        "scalar": T_scalar_overhead,
        "idle":   T_idle,
    }


def assign_confidence(spec: ModelSpec,
                      batch: int = 1,
                      params: "Mapping[str, float] | None" = None) -> str:
    """Heuristic confidence label for a prediction.

    Two modes:

    v6 mode (when params["v_model"] == "v6"): bucket-aware confidence based
    on Issue #2 v6 per-bucket calibration. Each bucket has validated OOS
    error magnitudes from VAL_size / VAL_batch evaluation:

        AIV_BOUND   high   — validated 12-26% err on Llama/Qwen2.5/SmolLM2
                             (cross-architecture decoder/swiglu from ModernBERT
                             encoder/GLU anchor)
        AIC_QWEN3   high   — Qwen3 prefill at S ≤ 1024; validated 14-28% err
        AIC_QWEN3   medium — Qwen3 prefill at S > 2048 (Qwen3-S4096-b1 was
                             -62% err in v6 VAL_size — within-bucket S
                             extrapolation)
        AIC_DECODE  medium — only 1 training anchor (Qwen3-decode)
        BALANCED    medium — only 2 training anchors (BERT, GPT-2)

    v4/v5 fallback (default when params absent): the original Issue #2 P1
    heuristic — see git history. Preserved for back-compat.
    """
    # Default to v4/v5 fallback if v_model not specified
    v_model = (params or {}).get("v_model", "v4")

    if v_model == "v7":
        from .physics_v7 import classify_bottleneck_v7
        bucket = classify_bottleneck_v7(spec, batch)
        if bucket == "AIV_BOUND":
            return ("high (v7 AIV_BOUND bucket: SDPA-calibrated, validated on "
                    "Llama/Qwen2.5/SmolLM2 + 5 Qwen3-sdpa configs)")
        if bucket == "AIC_DECODE":
            return ("medium (v7 AIC_DECODE: only Qwen3-decode-Min4 anchor)")
        return ("medium (v7 BALANCED bucket: BERT-S128 + GPT-2-S512 + short-S "
                "Qwen3-sdpa anchors)")

    if v_model == "v6":
        from .physics_v6 import classify_bottleneck
        bucket = classify_bottleneck(spec, batch)
        if bucket == "AIV_BOUND":
            return ("high (AIV_BOUND bucket: validated 12-26% err on 4 OOS "
                    "configs incl. Llama/Qwen2.5/SmolLM2)")
        if bucket == "AIC_QWEN3":
            if spec.S > 2048:
                return ("medium (AIC_QWEN3 bucket, S>2048: within-bucket S "
                        "extrapolation; Qwen3-S4096 had −62% err in v6 VAL)")
            return ("high (AIC_QWEN3 bucket: validated 5-28% err on Qwen3 "
                    "prefill multi-batch / multi-S configs)")
        if bucket == "AIC_DECODE":
            return ("medium (AIC_DECODE bucket: only Qwen3-decode-Min4-Skv128 "
                    "in training; new decoder/decode architectures may differ)")
        # BALANCED — default fallback bucket
        return ("medium (BALANCED bucket: only BERT-S128 + GPT-2-S512 anchors; "
                "novel small/shallow models may need further validation)")

    # ── v4/v5 path (legacy) ──
    w_proxy = (spec.layers * (4 * spec.d_model ** 2 + 3 * spec.d_model * spec.d_ff) * 2 / 1e6)
    is_large = w_proxy >= 600
    if spec.arch == "encoder":
        return "low (encoder: only BERT-S128 in training set)"
    if spec.ffn_type == "glu":
        return "low (GLU FFN: not in training set; aic_mte2 extrapolation untested)"
    if spec.S == 1:
        return "medium (decoder decode: 1 config in training; host_gap well-determined)"
    if is_large and 128 <= spec.S <= 8192 and spec.ffn_type in ("standard", "swiglu"):
        return (f"medium (large decoder prefill, weight_proxy≈{w_proxy:.0f}MB: relies on "
                f"heuristic 5.5× archetype amplification calibrated on Qwen3 only)")
    if 256 <= spec.S <= 4096 and spec.ffn_type in ("standard", "swiglu"):
        return "high (small/medium decoder prefill S∈[256,4096]: covered by GPT-2 + Qwen3 training)"
    if spec.S == 128 or spec.S == 8192:
        return "medium (boundary sequence length: minimal training coverage)"
    return "low (out-of-distribution; results are speculative)"


def _compute_h_prefill_sdpa(spec: ModelSpec, batch: int, n_kernels: int,
                            params: Mapping[str, float]) -> float:
    """Issue #11 — per-family multivariate host_gap for SDPA path.

      Qwen3 family: H = α_q + β_q × n_kernels + γ_q × (B × S)
      Other family: H = α_o + γ_o × (B × S)

    Falls back to legacy `H_prefill_us` if SDPA params not present(predicted
    against pre-Issue#11 param file).
    """
    if "H_prefill_sdpa_qwen3_alpha" not in params:
        return float(params["H_prefill_us"])  # back-compat
    BS = batch * spec.S
    if "Qwen3" in (spec.name or ""):
        a = float(params["H_prefill_sdpa_qwen3_alpha"])
        b = float(params["H_prefill_sdpa_qwen3_beta_nk"])
        g = float(params["H_prefill_sdpa_qwen3_gamma_BS"])
        return max(0.0, a + b * n_kernels + g * BS)
    a = float(params.get("H_prefill_sdpa_other_alpha", params["H_prefill_us"]))
    g = float(params.get("H_prefill_sdpa_other_gamma_BS", 0.0))
    return max(0.0, a + g * BS)


def predict_pipe_baseline(spec: ModelSpec,
                          arch: Mapping[str, float],
                          fitted_params: Mapping[str, float],
                          batch: int = 1,
                          eta_compute: float = 0.70,
                          attn_impl: str = "eager",
                          precision: str = "fp16",
                          mac_mult_override: "float | None" = None,
                          ideal_fixpipe: bool = False) -> Dict:
    """Predict the per-pipe baseline for one (model, arch, batch) triple.

    Args:
        attn_impl: "eager" (default, backward compat) or "sdpa". When "sdpa",
            host_gap uses the per-family multivariate fit from Issue #11
            (``H_prefill_sdpa_{qwen3,other}_*`` params). Eager configs continue
            using the legacy ``H_prefill_us`` constant.
        precision: "fp16" (default) | "int8" | "fp8" | "fp4". Rescales the
            CUBE/GEMM path only — weight+activation bytes by the dtype width and
            mac time by the cube throughput multiplier. The Vector(AIV) path and
            host/kernel scheduling are left at FP16 (mixed-precision keeps
            norm/softmax in FP16, and the kernel graph is unchanged).
        mac_mult_override: override the precision's cube throughput multiplier
            to model an asymmetric next-gen part (e.g. FP4 800T / FP8 200T → 4×).

    Returns a dict with the same shape as one entry under ``configs`` in
    ``data/calibration/pipe_baseline_per_model.json``, plus ``predicted: true``
    and a ``confidence`` label.
    """
    byte_factor, mac_mult, fixpipe_tax = _precision_factors(
        precision, mac_mult_override, ideal_fixpipe)
    total_ops, act_read, weight_b, output_b = compute_gemm_ops(spec)

    # Precision rescale (CUBE/GEMM path only): weights+activations stored at the
    # lower dtype width; output write requantized to the same width (the L0C
    # accumulator stays FP32, so this slightly under-counts fixpipe — a
    # second-order effect since BERT/ET-BERT's dominant AIC pipe is mte2/weights).
    act_read *= byte_factor
    weight_b *= byte_factor
    output_b *= byte_factor

    factor = float(batch)
    l2_bytes = arch["l2_mb"] * 1e6

    # MTE2 HBM traffic: weights are reloaded per inference (L2 is scratchpad,
    # not a cross-kernel cache), plus activation overflow above L2 capacity.
    weight_hbm_traffic = weight_b
    act_hbm_traffic = max(0.0, (act_read + output_b) * factor - l2_bytes * 0.3)

    aic_pipes = {
        # mac time divided by the precision throughput multiplier (FP8/INT8 do
        # 2× MACs/cycle, FP4 4×) — same silicon, denser packing at lower bits.
        "mac":     physics.aic_mac(total_ops * factor, arch, eta_compute=eta_compute) / mac_mult,
        "mte1":    physics.aic_mte1(act_read * factor, arch),
        "mte2":    physics.aic_mte2(weight_hbm_traffic, act_hbm_traffic, arch),
        # fixpipe carries the measured quantization requant tax (×1 for fp16,
        # ×2.65 int8/fp8, ×3.0 fp4); --ideal-fixpipe (next-gen) sets tax→1.
        "fixpipe": physics.aic_fixpipe(output_b * factor, arch) * fixpipe_tax,
        "scalar":  0.0,
    }

    # v_model dispatch: "v5" uses physics_v5 saturating formulas;
    # default keeps v4 (3-bucket archetype + continuous quad amp).
    v_model = str(fitted_params.get("v_model", "v4"))
    w_proxy = physics.weight_proxy_mb(spec.layers, spec.d_model, spec.d_ff)

    if v_model in ("v7", "v8"):
        # v8 reuses v7 schema (3-bucket SDPA-aware) — only fit objective differs.
        # v_model="v8" indicates multi-objective fit (wall + 0.3·AIC + 0.3·AIV + 0.2·n_kern),
        # vs v_model="v7" which is wall-only. predict path is identical.
        from . import physics_v7
        aic_pipes_base = dict(aic_pipes)
        aiv_data = _compute_aiv_data_dict(spec, batch)
        C_kernel = float(fitted_params.get("aiv_C_kernel_us", 16.0))
        C_data = float(fitted_params.get("aiv_C_data_us", 3.0))
        data_MB_v7 = (aiv_data["inter_bytes"] + aiv_data["output_bytes"]) / 1e6
        aiv_base_us = C_kernel * aiv_data["n_vector_kernels"] + C_data * data_MB_v7
        aic_time, aiv_time_v7, n_kernels, bucket = physics_v7.predict_v7(
            spec, arch, batch, fitted_params, aic_pipes_base, aiv_base_us)
        bp = physics_v7.get_bucket_params_v7(bucket, fitted_params)
        # Issue #9: aic_pipes breakdown 必须与 aic_time 同步缩放(后者在 predict_v7
        # 里已经乘了 hb["aic"]),否则下游 sweep 看到的分项与总和不一致。
        # v2: 用 per-component factor(AIC 桶用 aic factor,与 predict_v7 内部一致)
        _hb_aic = physics_v7.high_batch_efficiency_factors(batch)["aic"]
        aic_pipes = {k: v * bp["amp_aic"] * _hb_aic for k, v in aic_pipes.items()}
        active = aiv_time_v7 * 0.85
        aiv_pipes = {
            "vec":    round(active * 1/13, 1),
            "mte2":   round(active * 7/13, 1),
            "mte3":   round(active * 5/13, 1),
            "scalar": round(aiv_data["n_vector_kernels"] * 0.04, 1),
            "idle":   round(max(0, aiv_time_v7 - active - aiv_data["n_vector_kernels"] * 0.04), 1),
        }
        amp = bp["amp_aic"]
        aiv_model_tag = f"{'multi_obj_v8' if v_model == 'v8' else 'sdpa_aware_v7'}_{bucket}"

    elif v_model == "v6":
        from . import physics_v6
        # Compute physics base (no amp)
        aic_pipes_base = dict(aic_pipes)
        # AIV base from v4's formula with amp=1 (use predict_aiv_v2's base path)
        aiv_data = _compute_aiv_data_dict(spec, batch)
        C_kernel = float(fitted_params.get("aiv_C_kernel_us", 16.0))
        C_data = float(fitted_params.get("aiv_C_data_us", 3.0))
        data_MB_v6 = (aiv_data["inter_bytes"] + aiv_data["output_bytes"]) / 1e6
        aiv_base_us = C_kernel * aiv_data["n_vector_kernels"] + C_data * data_MB_v6
        aic_time, aiv_time_v6, n_kernels, bucket = physics_v6.predict_v6(
            spec, arch, batch, fitted_params, aic_pipes_base, aiv_base_us)
        # Apply amp uniformly to aic_pipes for visualization
        bp = physics_v6.get_bucket_params(bucket, fitted_params)
        aic_pipes = {k: v * bp["amp_aic"] for k, v in aic_pipes.items()}
        # Synthesize aiv_pipes proportionally (vec:mte2:mte3 = 1:7:5 from measured avg)
        active = aiv_time_v6 * 0.85
        aiv_pipes = {
            "vec":    round(active * 1/13, 1),
            "mte2":   round(active * 7/13, 1),
            "mte3":   round(active * 5/13, 1),
            "scalar": round(aiv_data["n_vector_kernels"] * 0.04, 1),
            "idle":   round(max(0, aiv_time_v6 - active - aiv_data["n_vector_kernels"] * 0.04), 1),
        }
        amp = bp["amp_aic"]
        aiv_model_tag = f"per_bucket_v6_{bucket}"
    elif v_model == "v5":
        from . import physics_v5
        from .model_spec import estimate_n_kernels_v5
        amp = physics_v5.archetype_amp_v5(w_proxy, spec.S, fitted_params)
        aic_pipes = {k: v * amp for k, v in aic_pipes.items()}
        # AIV serial sum (vec + mte2 + mte3 + scalar)
        aiv_data = _compute_aiv_data_dict(spec, batch)
        aiv_time_v5, aiv_pipes, _aiv_v5_telemetry = physics_v5.predict_aiv_v5(
            spec, arch, batch, fitted_params, aiv_data)
        n_kernels = estimate_n_kernels_v5(spec, fitted_params)
        aiv_model_tag = "physics_serial_v5"
    else:
        # v4 path (kept for back-compat + existing tests)
        amp = physics.archetype_amplification(w_proxy, spec.S)
        aic_pipes = {k: v * amp for k, v in aic_pipes.items()}
        aiv_pipes = predict_aiv_v2(spec, arch, fitted_params, batch)
        n_kernels = estimate_n_kernels(spec)
        aiv_model_tag = "continuous_amp_v4"
    is_decode = (spec.S == 1)
    # Issue #11: dispatch host_gap by (regime, attn_impl). Eager path keeps the
    # legacy single-constant H_prefill (backward compat); SDPA path uses the
    # per-family multivariate fit. Decode is unchanged (1 config in training set,
    # no SDPA vs eager distinction needed at S=1). n_kernels is already set by
    # the v_model branch above.
    if is_decode:
        H = float(fitted_params["H_decode_us"])
    elif attn_impl == "sdpa":
        H = _compute_h_prefill_sdpa(spec, batch, n_kernels, fitted_params)
    else:
        H = float(fitted_params["H_prefill_us"])
    K0 = float(fitted_params["K0_us_per_kernel"])

    aic_time = max(aic_pipes.values())
    # v3 pseudo-pipes are constructed so sum(all) = total aiv_time
    aiv_time = sum(aiv_pipes.values())
    kernel_gap = K0 * n_kernels
    host_gap = H
    wall_clock = aic_time + aiv_time + kernel_gap + host_gap

    dominant = max(aic_pipes, key=aic_pipes.get)

    return {
        "n_kernels_per_inf": n_kernels,
        "task_dur_us": aic_time + aiv_time,
        "aic_time_us": aic_time,
        "aiv_time_us": aiv_time,
        "aic_pipes_us": aic_pipes,
        "aiv_pipes_us": aiv_pipes,
        "aic_bubble_us": 0.0,    # not modeled analytically; populated by msprof if measured
        "aic_dominant_pipe": dominant,
        "wall_clock_us": wall_clock,
        "kernel_gap_us": kernel_gap,
        "host_gap_us": host_gap,
        "host_gap_us_per_kernel": (host_gap / n_kernels) if n_kernels else 0.0,
        "source": "predict_pipe_v2",
        "predicted": True,
        "confidence": assign_confidence(spec, batch=batch, params=fitted_params),
        "spec_summary": {
            "arch": spec.arch,
            "layers": spec.layers,
            "S": spec.S,
            "d_model": spec.d_model,
            "d_ff": spec.d_ff,
            "n_heads": spec.n_heads,
            "n_kv_heads": spec.n_kv_heads,
            "ffn_type": spec.ffn_type,
            "precision": precision.lower(),
            "precision_byte_factor": byte_factor,
            "precision_mac_mult": mac_mult,
            "fixpipe_quant_tax_mult": fixpipe_tax,
            "ideal_fixpipe": ideal_fixpipe,
            "weight_proxy_mb": round(w_proxy, 1),
            "archetype_amp": round(amp, 2),
            "aiv_model": aiv_model_tag,
            "aiv_n_vec_kernels": estimate_n_vector_kernels(spec),
            "aiv_C_kernel_us": float(fitted_params.get("aiv_C_kernel_us", 16.0)),
            "aiv_C_data_us": float(fitted_params.get("aiv_C_data_us", 3.0)),
            "aiv_attn_frac": round(_compute_aiv_data(spec, batch)[1], 3),
            "aiv_amp_computed": round(
                float(fitted_params.get("aiv_amp_decode", 1.5)) if spec.S == 1
                else max(0.1,
                         float(fitted_params.get("aiv_amp_a0", -0.2))
                         + float(fitted_params.get("aiv_amp_a1", 4.0))
                           * _compute_aiv_data(spec, batch)[1]  # attn_frac
                         + float(fitted_params.get("aiv_amp_a2", 14.0))
                           * (w_proxy / 1000.0) ** 2),
                3),
        },
    }


def predict_for_model_yaml(model_yaml: Path | str,
                           arch_yaml: Path | str,
                           fitted_params: Mapping[str, float],
                           batch: int = 1,
                           precision: str = "fp16",
                           mac_mult_override: "float | None" = None,
                           ideal_fixpipe: bool = False) -> Tuple[str, Dict]:
    """Convenience: load both YAMLs, predict, return (config_name, entry_dict)."""
    spec = ModelSpec.from_yaml(model_yaml)
    arch = _arch_dict_from_yaml(arch_yaml)
    entry = predict_pipe_baseline(spec, arch, fitted_params, batch=batch,
                                  precision=precision,
                                  mac_mult_override=mac_mult_override,
                                  ideal_fixpipe=ideal_fixpipe)
    # Use the model YAML's name field as the config key
    return spec.name, entry


def _load_params(params_path: Path) -> Dict[str, float]:
    """Load fitted params, with friendly hint if file is missing."""
    if not params_path.exists():
        raise FileNotFoundError(
            f"{params_path} not found. Run `prism-predict-pipe --refit-params` first "
            f"to fit K0/H_prefill/H_decode from "
            f"data/calibration/pipe_baseline_per_model.json."
        )
    with open(params_path, encoding="utf-8") as f:
        return json.load(f)


def _merge_into_baseline(merge_path: Path, config_name: str, entry: Dict) -> None:
    """Insert/overwrite the predicted entry into a baseline file (in-place)."""
    with open(merge_path, encoding="utf-8") as f:
        doc = json.load(f)
    if "configs" not in doc:
        # legacy flat dict: wrap it
        doc = {"configs": doc}
    doc["configs"][config_name] = entry
    with open(merge_path, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)


def compare_against_msprof(config_name: str, predicted: Dict, msprof_path: Path | str) -> Dict:
    """Compare a single predicted entry against measured msprof data.

    Reads ``msprof_path`` (same schema as pipe_baseline_per_model.json) and
    returns a dict with per-field err%, or ``{"available": False}`` if the
    config is not in the measured baseline.

    Ported forward from the Windows reviewer's prototype ``--msprof`` flag
    (commit b2ac2f5 on ``.sisyphus/predict_pipe_v0.1.py``).
    """
    with open(msprof_path, encoding="utf-8") as f:
        doc = json.load(f)
    configs = doc.get("configs", doc)
    if config_name not in configs:
        return {"available": False, "reason": f"{config_name!r} not in measured baseline"}
    meas = configs[config_name]

    def _err_pct(pred: float, actual: float) -> float:
        return abs(pred - actual) / actual * 100 if actual else 0.0

    return {
        "available": True,
        "wall_clock_us":     {"pred": predicted["wall_clock_us"],     "meas": meas["wall_clock_us"],     "err_pct": _err_pct(predicted["wall_clock_us"],     meas["wall_clock_us"])},
        "aic_time_us":       {"pred": predicted["aic_time_us"],       "meas": meas["aic_time_us"],       "err_pct": _err_pct(predicted["aic_time_us"],       meas["aic_time_us"])},
        "aiv_time_us":       {"pred": predicted["aiv_time_us"],       "meas": meas["aiv_time_us"],       "err_pct": _err_pct(predicted["aiv_time_us"],       meas["aiv_time_us"])},
        "host_gap_us":       {"pred": predicted["host_gap_us"],       "meas": meas["host_gap_us"],       "err_pct": _err_pct(predicted["host_gap_us"],       meas["host_gap_us"])},
        "kernel_gap_us":     {"pred": predicted["kernel_gap_us"],     "meas": meas["kernel_gap_us"],     "err_pct": _err_pct(predicted["kernel_gap_us"],     meas["kernel_gap_us"])},
        "n_kernels_per_inf": {"pred": predicted["n_kernels_per_inf"], "meas": meas["n_kernels_per_inf"], "err_pct": _err_pct(predicted["n_kernels_per_inf"], meas["n_kernels_per_inf"])},
    }


def _print_comparison_table(config_name: str, cmp: Dict) -> None:
    """Pretty-print the comparison dict from compare_against_msprof()."""
    if not cmp.get("available"):
        print(f"\nComparison vs msprof: {cmp.get('reason', 'unavailable')}")
        return
    print(f"\n=== Predicted vs Measured for {config_name} ===")
    print(f"{'Field':<22} {'Predicted':>12} {'Measured':>12} {'Err%':>8}")
    for field in ("wall_clock_us", "aic_time_us", "aiv_time_us",
                  "host_gap_us", "kernel_gap_us", "n_kernels_per_inf"):
        row = cmp[field]
        print(f"{field:<22} {row['pred']:>12,.0f} {row['meas']:>12,.0f} {row['err_pct']:>7.1f}%")


def main() -> int:
    p = argparse.ArgumentParser(
        description="Predict pipe baseline for a new model without msprof.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    repo = data_root_or_fallback()
    p.add_argument("--model",  help="Path to model YAML with gemm_spec: block.")
    p.add_argument("--arch",   default=str(repo / "arch" / "ascend_910b4_for_sweep_v2.yaml"),
                   help="Path to arch YAML (default: ascend_910b4_for_sweep_v2.yaml).")
    p.add_argument("--batch",  type=int, default=1, help="Batch size (default: 1).")
    p.add_argument("--precision", default="fp16", choices=sorted(_PRECISIONS),
                   help="Compute precision for the CUBE/GEMM path (default: fp16). "
                        "int8 is measurable on 910B; fp8/fp4 are next-gen proxies.")
    p.add_argument("--mac-mult", type=float, default=None,
                   help="Override the cube throughput multiplier for the chosen "
                        "precision (e.g. --precision fp4 --mac-mult 4 to model an "
                        "asymmetric next-gen part where FP4=800T / FP8=200T).")
    p.add_argument("--ideal-fixpipe", action="store_true",
                   help="Model a next-gen fixpipe that absorbs quant/dequant: "
                        "zero the measured quantization fixpipe tax (default keeps "
                        "the 910B-measured ×2.65/×3.0 requant overhead for int8/fp4).")
    p.add_argument("--output", help="Output JSON path. Default: data/calibration/predict_pipe_<name>.json")
    p.add_argument("--params",
                   default=str(repo / "data" / "calibration" / "predict_pipe_params.json"),
                   help="Fitted params JSON (from --refit-params).")
    p.add_argument("--refit-params", action="store_true",
                   help="Refit K0/H_prefill/H_decode from pipe_baseline_per_model.json "
                        "and save to --params path. Other args ignored.")
    p.add_argument("--pipe-baseline",
                   default=str(repo / "data" / "calibration" / "pipe_baseline_per_model.json"),
                   help="Input pipe baseline JSON for --refit-params.")
    p.add_argument("--merge-into", default=None,
                   help="If set, also merge prediction into this baseline JSON.")
    p.add_argument("--compare-against", default=None,
                   help="Path to a msprof baseline JSON. If the predicted "
                        "config_name appears in it, print a side-by-side "
                        "err%% table (ported from .sisyphus prototype --msprof).")
    p.add_argument("--config-name", default=None,
                   help="Override the config key used in the output JSON / "
                        "comparison lookup (default: model YAML 'name' field). "
                        "Use this to match an existing baseline JSON key "
                        "(e.g. 'BERT-base-S128-b1').")
    p.add_argument("--quiet", action="store_true", help="Suppress stdout summary.")
    args = p.parse_args()

    if args.refit_params:
        arch = _arch_dict_from_yaml(args.arch)
        params = fit_all_and_save(args.pipe_baseline, args.params, arch=arch)
        if not args.quiet:
            print(f"Fit complete → {args.params}")
            print(f"  K0       = {params['K0_us_per_kernel']:.4f} μs/kernel")
            print(f"  H_prefill= {params['H_prefill_us']:.0f} μs")
            print(f"  H_decode = {params['H_decode_us']:.0f} μs")
            print(f"  training: host_gap MAE = {params['training']['host_gap_mae_pct']:.1f}%, "
                  f"kernel_gap MAE = {params['training']['kernel_gap_mae_pct']:.1f}% "
                  f"(n={params['training']['n_configs']})")
            if "aiv_training" in params:
                print(f"  AIV fit:  MAE = {params['aiv_training']['mae_pct']:.1f}% "
                      f"(n={params['aiv_training']['n_configs']})")
        return 0

    if not args.model:
        p.error("--model is required (unless --refit-params)")

    params = _load_params(Path(args.params))
    config_name, entry = predict_for_model_yaml(
        args.model, args.arch, params, batch=args.batch,
        precision=args.precision, mac_mult_override=args.mac_mult,
        ideal_fixpipe=args.ideal_fixpipe)
    if args.config_name:
        config_name = args.config_name

    if not args.output:
        slug = config_name.lower().replace(" ", "_").replace("/", "_")
        prec_slug = "" if args.precision == "fp16" else f"_{args.precision}"
        args.output = str(repo / "data" / "calibration" / f"predict_pipe_{slug}{prec_slug}.json")

    output_doc = {
        "baseline_arch_name": Path(args.arch).stem,
        "baseline_arch_attrs": {},
        "configs": {config_name: entry},
    }
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(output_doc, f, ensure_ascii=False, indent=2)

    if args.merge_into:
        _merge_into_baseline(Path(args.merge_into), config_name, entry)

    cmp = None
    if args.compare_against:
        cmp = compare_against_msprof(config_name, entry, args.compare_against)

    if not args.quiet:
        print(f"Predicted {config_name} [precision={args.precision}"
              f"{f', mac_mult={args.mac_mult}' if args.mac_mult else ''}] → {args.output}")
        _mac = entry['aic_pipes_us'].get('mac'); _mte2 = entry['aic_pipes_us'].get('mte2')
        print(f"  aic_pipes  : mac={_mac:,.1f}  mte2(HBM)={_mte2:,.1f} μs")
        print(f"  aic_time   = {entry['aic_time_us']:>10,.0f} μs  (dominant: {entry['aic_dominant_pipe']})")
        print(f"  aiv_time   = {entry['aiv_time_us']:>10,.0f} μs")
        print(f"  kernel_gap = {entry['kernel_gap_us']:>10,.0f} μs ({entry['n_kernels_per_inf']} kernels × K0)")
        print(f"  host_gap   = {entry['host_gap_us']:>10,.0f} μs")
        print(f"  wall_clock = {entry['wall_clock_us']:>10,.0f} μs")
        print(f"  confidence = {entry['confidence']}")
        if args.merge_into:
            print(f"  merged into {args.merge_into}")
        if cmp is not None:
            _print_comparison_table(config_name, cmp)
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
